theme: jekyll-theme-leap-day
title: Capstone Project Proposal
show_downloads: true
titles_from_headings:
  enabled: false
author:
  name: "Mercedes Garcia"
  href: "git@github.com:ddc-java-10/capstone-project-proposal-2-Merced-es.git"
  